### ISSUE TITLE
Add a configuration repository for inspiration?

### ISSUE THREAD

**Issue by no-mood** [nix-community/nixvim#1299]
### Discussed in https://github.com/nix-community/nixvim/discussions/1295

<div type='discussions-op-text'>

<sup>Originally posted by **no-mood** March 20, 2024</sup>
Hi guys, I was starting to use nixvim (and nvim in general) and I was taking a look at the following [configuration](https://github.com/GaetanLepage/nix-config/tree/master/home/modules/tui/neovim).
Do you think it's a good idea to add a configuration repository, in the form of nix flakes, so that they can be grouped together and be used as inspiration?
Thank you very much</div>

**Comment by MattSturgeon** [comment]
I was thinking it might make sense to take inspiration from [kickstart.nvim](https://github.com/nvim-lua/kickstart.nvim), which is popular because it manages to cover the basics while remaining small & simple, but also including a ton of inline documentation explaining pretty much everything.

Maybe even directly port kickstart.nvim to nixvim more or less one-for-one (kickstart.nixvim 😂)?

It would probably make sense to include a kickstart style example in this repo (as a nix template), and have `nix check` test that the config is valid. That way it'd always be up to date with the latest breaking changes.

**Comment by hbjydev** [comment]
kickstart.nvim.nix 🤣

**Comment by no-mood** [comment]
I'd open to try and port it to nixvim, even without experience. What do you think? I could take less time for someone more experienced to do it.
If I start this project, what is the best approach?

**Comment by GaetanLepage** [comment]
I plan to give it a shot (maybe on stream) this WE. Your feedback, as a new user, will be very valuable of course.

**Comment by no-mood** [comment]
I'd love it! Keep us update, I'll participate for sure.
