### ISSUE TITLE
[PLUGIN REQUEST] nushell treesitter grammer

### ISSUE THREAD

**Issue by gabevenberg** [nix-community/nixvim#1319]
| Field    | Description |
|----------|-------------|
| Plugin   | `tree-sitter-nu`  | 
| Homepage | `https://github.com/nushell/tree-sitter-nu/tree/main`     | 
| Nixpkgs  | `https://search.nixos.org/packages?channel=23.11&show=tree-sitter-grammars.tree-sitter-nu&from=0&size=50&sort=relevance&type=packages&query=tree-sitter-nu` |

**Comment by siph** [comment]
I don't think there is an easy way to enable this without the grammar being included into [`tree-sitter`](https://github.com/tree-sitter/tree-sitter).

You can still add custom grammars, though. I am using this same grammar in my config here:
https://github.com/siph/nixvim-flake/blob/22166973ec14370830bfec5ee87c7bfcbbd3c946/config/treesitter/treesitter.nix

Here's the discussion about custom grammars: https://github.com/nix-community/nixvim/discussions/540

Note that you no longer need to build the nushell grammar because it's included in nixpkgs.

**Comment by GaetanLepage** [comment]
Here is what you need to do to get the `nushell` grammar in nixvim:
https://gist.github.com/GaetanLepage/7372ae30a27c40f2beb0019f1893f3b6

**Comment by GaetanLepage** [comment]
Yes, unfortunately we cannot do much here.
For the record, I will leave the final working configuration for adding nushell to nixvim: https://gist.github.com/GaetanLepage/7372ae30a27c40f2beb0019f1893f3b6
This is something you can do in your config, but we are not going to upstream it.
Of course, if the grammar gets added to treesitter, then we would defacto support it out of the box.
