### ISSUE TITLE
[PLUGIN REQUEST] improved-search.nvim

### ISSUE THREAD

**Issue by PowerUser64** [nix-community/nixvim#1338]
| Field    | Description |
|----------|-------------|
| Plugin   | improved-search.nvim  | 
| Homepage | [github:backdround/improved-search.nvim](https://github.com/backdround/improved-search.nvim)     | 
| Nixpkgs  | false | 

## Extra Information

Would be nice to have options to enable some (or all) of the suggested configuration options presented in the readme, as I think most people will use it in this way.

**Comment by GaetanLepage** [comment]
Made a PR to nixpkgs: https://github.com/NixOS/nixpkgs/pull/299697

**Comment by PowerUser64** [comment]
Woah cool, how'd you do that? I see that `pkgs/applications/editors/vim/plugins/generated.nix` is modified in the PR, but I'm guessing that was generated from `pkgs/applications/editors/vim/plugins/vim-plugin-names`? What did you do to generate it?

**Comment by GaetanLepage** [comment]
The first step is to add the plugin to `vim-plugin-names`.
This can be done by running:
```
nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater add OWNER/PLUGIN_REPO'
```
Then, the `generated.nix` file has to be populated with the new plugin.
Theoretically, you should do it by running the script without argument.
```
nix-shell -p vimPluginsUpdater --run 'vim-plugins-updater'
```
This will update the entire `generated.nix` file according to the `vim-plugin-names` list.
In practice, I prefer to manually writing the snippet corresponding to my plugin in `generated.nix`.
Indeed, running the update script updates all the plugins, which requires a github token and a lot of time (~15min) to run.
Also, it is better for PRs that aim at adding a new plugin to do just that, without the risk of introducing a regression caused by a plugin update.

Resources: https://nixos.org/manual/nixpkgs/stable/#adding-new-plugins-to-nixpkgs

**Comment by PowerUser64** [comment]
Woah, cool! Thanks for explanation!
