### ISSUE TITLE
Question - how to reload a new config after rebuilding in a running neovim instance?

### ISSUE THREAD

**Issue by idrisr** [nix-community/nixvim#1437]
Is it possible to reload a running neovim with the new config generated from the building nixvim?

My process is often something like

1) edit some text in nixvim neovim
2) realize I need a change in my config
3) make the change, and rebuild the nixvim package
4) at this point, with non-nixvim neovim or vim, I could do a `:source ~/.vimrc`  of `:source ~/.config/initl.lua` in the running neovim instance, without having to enter and exit neovim.

With nixvim, I haven't figure out if this is possible. From reading the wrapper script found via `readpath $(which nvim$)`, it appears the config file is only in the nix store, and not someplace like `~/.config/nvim` which is constant even after rebuilds.

```
exec -a "$0" "/nix/store/84k4krd57x09nixwzcwx93wvd40ih4f0-neovim-unwrapped-0.9.5/bin/nvim"  \
--cmd "lua vim.g.loaded_node_provider=0;vim.g.loaded_perl_provider=0;vim.g.loaded_python_provider=0;vim.g.python3_host_prog='/nix/store/rn6wipcqs10lqr0w8yahm1zqljm33qck-neovim-0.9.5/bin/nvim-python3';vim.g.ruby_host_prog='/nix/store/rn6wipcqs10lqr0w8yahm1zqljm33qck-neovim-0.9.5/bin/nvim-ruby'" \
--cmd "set packpath^=/nix/store/fx8arbli2yjgiid9z72r6s63c74lrjh7-vim-pack-dir" \
--cmd "set rtp^=/nix/store/fx8arbli2yjgiid9z72r6s63c74lrjh7-vim-pack-dir" \
-u /nix/store/m84i7ci47lz3avkn3jnyyb0sc5zhkjhx-init.lua "$@" 
```

**Comment by no-mood** [comment]
What about a NixVim flake? Put your config in a flake and then rebuild it. To speed up the process, you could use direnv.

**Comment by idrisr** [comment]
Yes, using a flake for the nixvim module is possible, and that would still require restarting any running instances of neovim for the new config to take place. Or am I missing something in what you're saying? Does your solution allow a running version of neovim to be reloaded with the new config, without entering and exiting?

**Comment by GaetanLepage** [comment]
> Yes, using a flake for the nixvim module is possible, and that would still require restarting any running instances of neovim for the new config to take place. Or am I missing something in what you're saying? Does your solution allow a running version of neovim to be reloaded with the new config, without entering and exiting?

No this is indeed a different thing.
A standalone flake, allows you to rebuild your configuration faster (because you are not reloading your entire NixOS/HM config every time). However, it doesn't change anything regarding your original issue.

Technically, you can definitely source your `init.lua` as if you were not using nixvim. There are a few issues though:
- It might not be at `~/.config/nvim/init.lua`. It will only be there if you use the HM module. Otherwise (standalone flake), it will be somewhere in the `/nix/store`. (If you are using the NixOS module, it will be at `/etc/nvim/sysinit.lua`).
- When using nixvim, your neovim configuration is more than your `init.lua`. The `nvim` executable generated by nixvim is actually a shell script that wraps the neovim binary. This will probably be affected if you change your config, and thus requiring you to restart neovim to get the changes. Especially, if you add a new plugin, re-sourcing your `init.lua` won't be enough.

Personally, I don't change my neovim config too often. Of course, you will tinker at the beginning to test some plugins/options etc, but once your setup will have converged, it won't be too much of an issue. At least, that is my experience.

Feel free to close the issue if I this answer was satisfying :)

**Comment by idrisr** [comment]
Ok, understood. From inspecting the neovim command that was generated from nixvim, I could see that it was indeed a shell script being wrapped several times for path adjustments and other flags.  There's other solutions to this, like using `https://github.com/tpope/vim-obsession`. I'll still have to restart neovim, but won't be a big deal as I can save its current state before doing so. I'll close the issue.  Thanks!
