### ISSUE TITLE
[BUG] `extraPackages` not installing named packages in `PATH`

### ISSUE THREAD

**Issue by alesauce** [nix-community/nixvim#1560]
| Field        | Description |
|--------------|-------------|
| Plugin       | `nvim-jdtls`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `unstable` | 

- [ X ] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

I am attempting to install `jdt-language-server` using the `extraPackages` attribute from nixvim. However, it is not getting installed in my system's `PATH` and when I attempt to work on java files I am getting the below error.

Error message:
```
...-unwrapped-0.10.0/share/nvim/runtime/lua/vim/lsp/rpc.lua:800: Spawning language server with cmd: `{ "/nix/store/kdcixm66j8x01g6dn2j7vbz89r7dks2r-jdt-language-server-1.31.0/bin/jdt-language-server", "--jvm-arg=-javaagent:/Users/alesauce/Developer/lombok.jar", "-data", "/Users/alesauce/.local/share/eclipse/nix-home", "--add-modules=ALL-SYSTEM" }` failed. The language server is either not installed, missing from PATH, or not executable.
```

I have also tried building my nixvim flake directly, and jdt-language-server is still not available in the path then.

[File adding jdt-language-server](https://github.com/alesauce/nixvim-flake/blob/main/config/core.nix#L53)
[nvim-jdtls setup file](https://github.com/alesauce/nixvim-flake/blob/main/config/lsp/nvim-jdtls.nix)

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
    config.extraPackages = with pkgs; [
      jdt-language-server
    ];
    files."ftplugin/java.lua" = {
            plugins.nvim-jdtls = {
      enable = true;
      data = ".idea/nvim-jdtls";
    };
    extraConfigLua = ''
              local config = {
       capabilities = capabilities,
       cmd = {
        "${pkgs.jdt-language-server}/bin/jdt-language-server",
        "--jvm-arg=-javaagent:" .. home .. "/Developer/lombok.jar",
        "-data",
        eclipse_workspace,
        "--add-modules=ALL-SYSTEM",
       },
      }

      jdtls.start_or_attach(config)
    '';
    };
}
```

**Comment by MattSturgeon** [comment]
Looks like you're using the wrong binary in your cmd; `bin/jdt-language-server`.

`getExe` returns `bin/jdtls` instead:

```
> lib.getExe pkgs.jdt-language-server
"/nix/store/zhhxd2xzmrxaincy4ygs1402v3mvg82g-jdt-language-server-1.31.0/bin/jdtls"
```

Try changing the first element of your `cmd` table to `"${lib.getExe pkgs.jdt-language-server}"` or `"${pkgs.jdt-language-server}/bin/jdtls"`.

Personally, I try and use `lib.getExe` whenever possible instead of manually typing the `/bin/exe` path, since that function will use whatever the package maintainer has configured for the binary name.

As an aside, this doesn't relate to your `PATH`, since `${pkgs.jdt-language-server}` will be an absolute path (e.g. `/nix/store/kdcixm66j8x01g6dn2j7vbz89r7dks2r-jdt-language-server-1.31.0`).

**Comment by alesauce** [comment]
You were 100% right, and thank you for teaching me something new! Switched to `"${lib.getExe pkgs.jdt-language-server}"`.
