### ISSUE TITLE
[BUG] Can't unset Incremental selection keymaps with `<action_name>=false`

### ISSUE THREAD

**Issue by ugur-a** [nix-community/nixvim#1911]
| Field        | Description |
|--------------|-------------|
| Plugin       | treesitter  |
| Nixpkgs      | unstable |
| Home Manager | unstable |

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description
According to the [Incremental selection docs](https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#incremental-selection), it should be possible to set the value to `false` in order to unset the corresponding keymap. But in the Nixvim module, the keymap options are defined as follows:
https://github.com/nix-community/nixvim/blob/d2f733efb4962903b77af330c4c03a63f2f72968/plugins/languages/treesitter/treesitter.nix#L119-L129
where, in particular, the helper function `mkKeymap`, defined at line 121, doesn't accept `false`. Setting it to `null` doesn't work either - the plugin default keymap gets created.

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  enable = true;
  plugins.treesitter = {
  enable = true;
    settings = {
      incremental_selection = {
        enable = true;
        keymaps = {
          init_selection = false;
        };
      };
    };
  };
};
```

**Comment by MattSturgeon** [comment]
I think this just got missed, since the documentation is kinda hidden in an inline comment within an example.

Since we declare a "str" type option, you won't be able to define a boolean until we fix it.

This is one reason sometimes it's better for us not to provide options and instead rely on freeform definitions...

Temporarily, you can work around this using raw lua:

```nix

keymaps = {
  init_selection.__raw = "false";
};
```
