### ISSUE TITLE
[BUG] `disallowedRequisites` is used on a derivation that doesn't support it

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/nixvim#2037]
This is printed while evaluating the tests:

```
warning: In a derivation named 'neovim-unwrapped-0.10.1',
'structuredAttrs' disables the effect of the derivation attribute 'disallowedRequisites';
use 'outputChecks.<output>.disallowedRequisites' instead
```

It's probably an upstream issue, but creating a ticket here first.

`rg 'disallowedRequisites'` didn't find any matches in our repo and the error message seems to relate to the neovim-unwrapped package in nixpkgs.

First discussed https://github.com/nix-community/nixvim/pull/2035#issuecomment-2295036601

**Comment by khaneliman** [comment]
We talked about it on matrix, but figured I'd post here for visibility and tracking. Saw conversation in discord https://discord.com/channels/568306982717751326/1244007773948346468/1262647913113452574 talking about the combination of [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ne/neovim-unwrapped/package.nix#L71) and [this](https://github.com/NixOS/nixpkgs/blob/master/pkgs%2Fby-name%2Fne%2Fneovim-unwrapped%2Fpackage.nix#L150) upstream.

**Comment by magneticflux-** [comment]
This issue was exposed by https://github.com/NixOS/nix/pull/10884 in , but the issue has existed since  https://github.com/NixOS/nixpkgs/pull/281176 was merged January 2024 and https://github.com/NixOS/nixpkgs/pull/258705 was merged May 2024.

It was originally noticed in https://github.com/nix-community/neovim-nightly-overlay/issues/579, which resulted in https://github.com/NixOS/nixpkgs/pull/330026, which was then closed in favor of https://github.com/NixOS/nixpkgs/pull/334915, which was merged into staging 4 days ago.

You can track the progress of the final PR here: https://nixpk.gs/pr-tracker.html?pr=334915
