### ISSUE TITLE
[BUG] `plugins.lsp.servers.prismals.package` was accessed but has no value defined

### ISSUE THREAD

**Issue by blackxored** [nix-community/nixvim#2405]
| Field        | Description |
|--------------|-------------|
| Plugin       | `lsp`  | 
| Nixpkgs      | `unstable` | 
| Home Manager | `24.05` | 

- [x] I have read the [FAQ](https://nix-community.github.io/nixvim/user-guide/faq.html) and my bug is not listed there.

## Description

```
error: The option `plugins.lsp.servers.prismals.package' was accessed but has no value defined. Try setting the option.
```

## Minimal, Reproducible Example (MRE)

```nix
programs.nixvim = {
  plugins.lsp = {
    servers = {
       prismals.enable = true;
    };
    extraPlugins = with pkgs.vimPlugins; [
      nvim-lspconfig
    ];
  };
}
```

I don't use this, but I believe it was part of the flake template.

**Comment by MattSturgeon** [comment]
This is an intentional result of #2403. `prismals` is listed as "unpackaged" in https://github.com/nix-community/nixvim/blob/main/plugins/lsp/lsp-packages.nix, which means end-users must explicitly either provide their own package or set the package option to `null`.

```diff
   servers = {
      prismals.enable = true;
+     prismals.package = null;
   };
```

Also, note that you should really be using `plugins.lsp.enable` instead of `extraPlugins`.

Is there anything special about prismals that means it doesn't need a package? We could add a "doesn't need a package" category to `lsp-packages.nix`.

cc @traxys

**Comment by blackxored** [comment]
Thanks for the quick reply. I'm not familiar with `prismals` but I think the expectation for me was that `package` was something I would use to override, and `enable` would work without it. That seems to be the case with other parts of the config?

**Comment by traxys** [comment]
I don't think there are any LSPs that "don't need a package", it's just that a lot of them are not in nixpkgs. We simply made explicit something that was implicit: You need to do actions on your side to install this, nixvim can't do it automatically

**Comment by khaneliman** [comment]
I agree it’s not the greatest UX. I think we should do something to warn the user instead of throwing an evaluation error.

**Comment by MattSturgeon** [comment]
> I agree it’s not the greatest UX. I think we should do something to warn the user or throw an assertion explaining the issue instead of the default evaluation error. 

Agreed, but this applies to all of our generated options (none-ls, efmls, lsp-servers). Let's open a dedicated issue to track that.
