### ISSUE TITLE
Plugin Request: VTSLS

### ISSUE THREAD

**Issue by fabianpage** [nix-community/nixvim#535]
**Plugin**: vtsls
**Plugin repository**: [vtsls](https://github.com/yioneko/vtsls)
**Is the plugin on nixpkgs**: No

## Extra information
It would be nice to have a language server for Typescript

**Comment by siph** [comment]
There already exists [tsserver](https://nix-community.github.io/nixvim/plugins/lsp/servers/tsserver/index.html) for typescript.

It also looks like `vtsls` has an [additional plugin](https://github.com/yioneko/nvim-vtsls).

**Comment by GaetanLepage** [comment]
> There already exists [tsserver](https://nix-community.github.io/nixvim/plugins/lsp/servers/tsserver/index.html) for typescript.
True ! @fabianpage is there a specific reason to use vtsls rather than tsserver ? (Genuine question, I have never done typescript personally).


> It also looks like `vtsls` has an [additional plugin](https://github.com/yioneko/nvim-vtsls).
Sure, but it is not needed to work with vtsls. `nvim-lspconfig` [already has a configuration for it](https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.txt#vtsls).

Finally, `vtsls` itself is not packaged in Nixvim. It is a node package and I don't have the knowledge to package it.
I gave it a quick try and was not able to get very far...
If you feel like doing it, please go on. I will be keen on adding the nixvim lspconfig support for it afterwards.

**Comment by fabianpage** [comment]
Sorry, tsserver is perfectly fine. I missed it in the search, probably PEBKAC...
